---
title: "Rotenone Mortality"
author: "Vincent Tam"
date: "February 12, 2019"
output: html_document
---

```{r echo = FALSE, warning = FALSE, message = FALSE}
## non-linear regression, use dead data instead of mortality rate
## Libraries, Set Up Graphics Parameters, Upload Data Set
library(tidyverse)
library(dplyr)
library(janitor)
library(broom)
library(modelr)
library(httk)
library(drc)
library(ggplot2)
library(GGally)
library(MASS)
library(plotly)
library(knitr)
library(tables)
library(viridis)
library(flexdashboard)
par(mar = c(1,1,1,1))
mortality = read_csv("./RotenoneMortalityRateLogged.csv")
```
### Replication 1
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 1 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead1 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 1 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead1)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead1 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 1 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead1 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 1, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead1)
## Fitted Values - Log Concentration vs Grp 1 Dead
fit1log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 1 Dead`)
tidy(fit1log)
augment(fit1log)
glance(fit1log)
fitted(fit1log)
fit1log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 1 Dead
pred1log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 1 Dead`, family = binomial(link = "logit"))
summary(pred1log)
predict(pred1log, type = "response")
pred1log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred1log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 1 Dead`, Fitted = fitted(fit1log), Predicted = predict(pred1log, type = "response"))
## ggpairs Relationships Between Group 1 Variables
d1 <- highlight_key(iris)
p1 <- ggpairs(data = mortality, columns = 1:5, title = "Group 1 - Relationship between predictor and response variables")
ggplotly(p1) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 1 Dead
Fitted_Res_Hist1 = ggplot(data = mortality, aes(fit1log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 1 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist1)
## Linear Fitted Model - Log Concentration vs Grp 1 Dead
Lin_Fit_Log1 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 1 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 1 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log1)
```
### Replication 2
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 2 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead2 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 2 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead2)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead2 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 2 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead2 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 2, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead1)
## Fitted Values - Log Concentration vs Grp 2 Dead
fit2log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 2 Dead`)
tidy(fit2log)
augment(fit2log)
glance(fit2log)
fitted(fit2log)
fit2log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 2 Dead
pred2log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 2 Dead`, family = binomial(link = "logit"))
summary(pred2log)
predict(pred2log, type = "response")
pred2log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred2log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 2 Dead`, Fitted = fitted(fit2log), Predicted = predict(pred2log, type = "response"))
## ggpairs Relationships Between Group 2 Variables
d2 <- highlight_key(iris)
p2 <- ggpairs(data = mortality, columns = 1:5, title = "Group 2 - Relationship between predictor and response variables")
ggplotly(p2) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 2 Dead
Fitted_Res_Hist2 = ggplot(data = mortality, aes(fit2log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 2 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist2)
## Linear Fitted Model - Log Concentration vs Grp 2 Dead
Lin_Fit_Log2 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 2 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 2 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log2)
```
### Replication 3
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 3 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead3 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 3 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead3)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead3 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 3 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead3 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 3, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead3)
## Fitted Values - Log Concentration vs Grp 3 Dead
fit3log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 3 Dead`)
tidy(fit3log)
augment(fit3log)
glance(fit3log)
fitted(fit3log)
fit3log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 3 Dead
pred3log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 3 Dead`, family = binomial(link = "logit"))
summary(pred3log)
predict(pred3log, type = "response")
pred3log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred3log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 3 Dead`, Fitted = fitted(fit3log), Predicted = predict(pred3log, type = "response"))
## ggpairs Relationships Between Group 3 Variables
d3 <- highlight_key(iris)
p3 <- ggpairs(data = mortality, columns = 1:5, title = "Group 3 - Relationship between predictor and response variables")
ggplotly(p3) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 3 Dead
Fitted_Res_Hist3 = ggplot(data = mortality, aes(fit3log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 3 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist3)
## Linear Fitted Model - Log Concentration vs Grp 3 Dead
Lin_Fit_Log3 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 3 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 3 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log3)
```
### Replication 4
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 4 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead4 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 4 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead4)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead4 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 4 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead4 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 4, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead4)
## Fitted Values - Log Concentration vs Grp 4 Dead
fit4log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 4 Dead`)
tidy(fit4log)
augment(fit4log)
glance(fit4log)
fitted(fit4log)
fit4log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 4 Dead
pred4log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 4 Dead`, family = binomial(link = "logit"))
summary(pred4log)
predict(pred4log, type = "response")
pred4log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred4log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 4 Dead`, Fitted = fitted(fit4log), Predicted = predict(pred4log, type = "response"))
## ggpairs Relationships Between Group 4 Variables
d4 <- highlight_key(iris)
p4 <- ggpairs(data = mortality, columns = 1:5, title = "Group 4 - Relationship between predictor and response variables")
ggplotly(p4) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 4 Dead
Fitted_Res_Hist4 = ggplot(data = mortality, aes(fit1log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 4 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist4)
## Linear Fitted Model - Log Concentration vs Grp 4 Dead
Lin_Fit_Log4 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 4 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 4 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log4)
```
### Replication 5
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 5 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead5 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 5 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead5)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead5 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 5 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead5 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 5, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead5)
## Fitted Values - Log Concentration vs Grp 5 Dead
fit5log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 5 Dead`)
tidy(fit5log)
augment(fit5log)
glance(fit5log)
fitted(fit5log)
fit5log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 5 Dead
pred5log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 5 Dead`, family = binomial(link = "logit"))
summary(pred5log)
predict(pred5log, type = "response")
pred5log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred5log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 5 Dead`, Fitted = fitted(fit5log), Predicted = predict(pred5log, type = "response"))
## ggpairs Relationships Between Group 5 Variables
d5 <- highlight_key(iris)
p5 <- ggpairs(data = mortality, columns = 1:5, title = "Group 5 - Relationship between predictor and response variables")
ggplotly(p5) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 5 Dead
Fitted_Res_Hist5 = ggplot(data = mortality, aes(fit5log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 5 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist5)
## Linear Fitted Model - Log Concentration vs Grp 5 Dead
Lin_Fit_Log5 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 5 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 1 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log5)
```
### Replication 6
```{r echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
## Replication 6 - Logged Concentration Test Code
## Normal Plot - Concentration vs Dead
Norm_Conc_Dead6 = ggplot(mortality, aes(`Concentration (micromolar)`, `Grp 6 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
ggplotly(Norm_Conc_Dead6)
## Local Regression - 50% smoothing span of Log Concentration with Dead
Regress_LogConc_Dead6 = ggplot(mortality, aes(`Log Concentration (micromolar)`, `Grp 6 Dead`)) + geom_point(size = 2) + geom_smooth(span = 0.5)
Regress_LogConc_Dead6 + scale_x_log10() + xlim(-10, 10) + labs(title = "Replication 6, Rotenone   Dose-Response Curve")
ggplotly(Regress_LogConc_Dead6)
## Fitted Values - Log Concentration vs Grp 6 Dead
fit6log = lm(mortality$`Log Concentration (micromolar)` ~ mortality$`Grp 6 Dead`)
tidy(fit6log)
augment(fit6log)
glance(fit6log)
fitted(fit6log)
fit6log %>% 
  broom::tidy()
## Predicted Values - Log Concentration vs Grp 6 Dead
pred6log = glm(factor(mortality$`Log Concentration (micromolar)`) ~ mortality$`Grp 6 Dead`, family = binomial(link = "logit"))
summary(pred6log)
predict(pred6log, type = "response")
pred6log %>%
  broom::tidy()
## LD50 based on Predicted Value
dose.p(pred6log,p = 0.5)
## Concentration, Mortality, Fitted, Predicted Chart
data.frame(Concentration = mortality$`Log Concentration (micromolar)`, Mortality = mortality$`Grp 6 Dead`, Fitted = fitted(fit6log), Predicted = predict(pred6log, type = "response"))
## ggpairs Relationships Between Group 1 Variables
d6 <- highlight_key(iris)
p6 <- ggpairs(data = mortality, columns = 1:5, title = "Group 6 - Relationship between predictor and response variables")
ggplotly(p6) %>% 
highlight("plotly_selected")
## Fitted Model Residuals - Histogram Log Concentration vs Grp 1 Dead
Fitted_Res_Hist6 = ggplot(data = mortality, aes(fit6log$residuals)) + 
  geom_histogram(binwidth = 0.25, color = "black", fill = "purple4") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Histogram for Group 6 Fitted Model Residuals") 
ggplotly(Fitted_Res_Hist6)
## Linear Fitted Model - Log Concentration vs Grp 6 Dead
Lin_Fit_Log6 = ggplot(data = mortality, aes(x = `Log Concentration (micromolar)`, y = `Grp 6 Dead`)) + geom_point() +
  stat_smooth(method = "lm", col = "dodgerblue3") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line.x = element_line(),
        axis.line.y = element_line()) +
  ggtitle("Replication 6 Linear Model Fitted to Data")
ggplotly(Lin_Fit_Log6)
```